// https://raw.githubusercontent.com/lukes/ISO-3166-Countries-with-Regional-Codes/master/slim-2/slim-2.json
export default function () {
  return [
    {
      "locale": "en",
      "countries": {
        "AF": "Afghanistan",
        "AL": "Albania",
        "DZ": "Algeria",
        "AS": "American Samoa",
        "AD": "Andorra",
        "AO": "Angola",
        "AI": "Anguilla",
        "AQ": "Antarctica",
        "AG": "Antigua and Barbuda",
        "AR": "Argentina",
        "AM": "Armenia",
        "AW": "Aruba",
        "AU": "Australia",
        "AT": "Austria",
        "AZ": "Azerbaijan",
        "BS": "Bahamas",
        "BH": "Bahrain",
        "BD": "Bangladesh",
        "BB": "Barbados",
        "BY": "Belarus",
        "BE": "Belgium",
        "BZ": "Belize",
        "BJ": "Benin",
        "BM": "Bermuda",
        "BT": "Bhutan",
        "BO": "Bolivia",
        "BA": "Bosnia and Herzegovina",
        "BW": "Botswana",
        "BV": "Bouvet Island",
        "BR": "Brazil",
        "IO": "British Indian Ocean Territory",
        "BN": "Brunei Darussalam",
        "BG": "Bulgaria",
        "BF": "Burkina Faso",
        "BI": "Burundi",
        "KH": "Cambodia",
        "CM": "Cameroon",
        "CA": "Canada",
        "CV": "Cape Verde",
        "KY": "Cayman Islands",
        "CF": "Central African Republic",
        "TD": "Chad",
        "CL": "Chile",
        "CN": ["People's Republic of China", "China"],
        "CX": "Christmas Island",
        "CC": "Cocos (Keeling) Islands",
        "CO": "Colombia",
        "KM": "Comoros",
        "CG": ["Republic of the Congo", "Congo"],
        "CD": ["Democratic Republic of the Congo", "Congo"],
        "CK": "Cook Islands",
        "CR": "Costa Rica",
        "CI": ["Cote D'Ivoire","Ivory Coast"],
        "HR": "Croatia",
        "CU": "Cuba",
        "CY": "Cyprus",
        "CZ": ["Czech Republic", "Czechia"],
        "DK": "Denmark",
        "DJ": "Djibouti",
        "DM": "Dominica",
        "DO": "Dominican Republic",
        "EC": "Ecuador",
        "EG": "Egypt",
        "SV": "El Salvador",
        "GQ": "Equatorial Guinea",
        "ER": "Eritrea",
        "EE": "Estonia",
        "ET": "Ethiopia",
        "FK": "Falkland Islands (Malvinas)",
        "FO": "Faroe Islands",
        "FJ": "Fiji",
        "FI": "Finland",
        "FR": "France",
        "GF": "French Guiana",
        "PF": "French Polynesia",
        "TF": "French Southern Territories",
        "GA": "Gabon",
        "GM": ["Republic of The Gambia", "The Gambia", "Gambia"],
        "GE": "Georgia",
        "DE": "Germany",
        "GH": "Ghana",
        "GI": "Gibraltar",
        "GR": "Greece",
        "GL": "Greenland",
        "GD": "Grenada",
        "GP": "Guadeloupe",
        "GU": "Guam",
        "GT": "Guatemala",
        "GN": "Guinea",
        "GW": "Guinea-Bissau",
        "GY": "Guyana",
        "HT": "Haiti",
        "HM": "Heard Island and McDonald Islands",
        "VA": "Holy See (Vatican City State)",
        "HN": "Honduras",
        "HK": "Hong Kong",
        "HU": "Hungary",
        "IS": "Iceland",
        "IN": "India",
        "ID": "Indonesia",
        "IR": ["Islamic Republic of Iran", "Iran"],
        "IQ": "Iraq",
        "IE": "Ireland",
        "IL": "Israel",
        "IT": "Italy",
        "JM": "Jamaica",
        "JP": "Japan",
        "JO": "Jordan",
        "KZ": "Kazakhstan",
        "KE": "Kenya",
        "KI": "Kiribati",
        "KP": "North Korea",
        "KR": ["South Korea", "Korea, Republic of", "Republic of Korea"],
        "KW": "Kuwait",
        "KG": "Kyrgyzstan",
        "LA": "Lao People's Democratic Republic",
        "LV": "Latvia",
        "LB": "Lebanon",
        "LS": "Lesotho",
        "LR": "Liberia",
        "LY": "Libya",
        "LI": "Liechtenstein",
        "LT": "Lithuania",
        "LU": "Luxembourg",
        "MO": "Macao",
        "MG": "Madagascar",
        "MW": "Malawi",
        "MY": "Malaysia",
        "MV": "Maldives",
        "ML": "Mali",
        "MT": "Malta",
        "MH": "Marshall Islands",
        "MQ": "Martinique",
        "MR": "Mauritania",
        "MU": "Mauritius",
        "YT": "Mayotte",
        "MX": "Mexico",
        "FM": "Micronesia, Federated States of",
        "MD": "Moldova, Republic of",
        "MC": "Monaco",
        "MN": "Mongolia",
        "MS": "Montserrat",
        "MA": "Morocco",
        "MZ": "Mozambique",
        "MM": "Myanmar",
        "NA": "Namibia",
        "NR": "Nauru",
        "NP": "Nepal",
        "NL": "Netherlands",
        "NC": "New Caledonia",
        "NZ": "New Zealand",
        "NI": "Nicaragua",
        "NE": "Niger",
        "NG": "Nigeria",
        "NU": "Niue",
        "NF": "Norfolk Island",
        "MK": ["The Republic of North Macedonia", "North Macedonia"],
        "MP": "Northern Mariana Islands",
        "NO": "Norway",
        "OM": "Oman",
        "PK": "Pakistan",
        "PW": "Palau",
        "PS": ["State of Palestine", "Palestine"],
        "PA": "Panama",
        "PG": "Papua New Guinea",
        "PY": "Paraguay",
        "PE": "Peru",
        "PH": "Philippines",
        "PN": "Pitcairn",
        "PL": "Poland",
        "PT": "Portugal",
        "PR": "Puerto Rico",
        "QA": "Qatar",
        "RE": "Reunion",
        "RO": "Romania",
        "RU": ["Russian Federation", "Russia"],
        "RW": "Rwanda",
        "SH": "Saint Helena",
        "KN": "Saint Kitts and Nevis",
        "LC": "Saint Lucia",
        "PM": "Saint Pierre and Miquelon",
        "VC": "Saint Vincent and the Grenadines",
        "WS": "Samoa",
        "SM": "San Marino",
        "ST": "Sao Tome and Principe",
        "SA": "Saudi Arabia",
        "SN": "Senegal",
        "SC": "Seychelles",
        "SL": "Sierra Leone",
        "SG": "Singapore",
        "SK": "Slovakia",
        "SI": "Slovenia",
        "SB": "Solomon Islands",
        "SO": "Somalia",
        "ZA": "South Africa",
        "GS": "South Georgia and the South Sandwich Islands",
        "ES": "Spain",
        "LK": "Sri Lanka",
        "SD": "Sudan",
        "SR": "Suriname",
        "SJ": "Svalbard and Jan Mayen",
        "SZ": "Eswatini",
        "SE": "Sweden",
        "CH": "Switzerland",
        "SY": "Syrian Arab Republic",
        "TW": ["Taiwan, Province of China", "Taiwan"],
        "TJ": "Tajikistan",
        "TZ": ["United Republic of Tanzania", "Tanzania"],
        "TH": "Thailand",
        "TL": "Timor-Leste",
        "TG": "Togo",
        "TK": "Tokelau",
        "TO": "Tonga",
        "TT": "Trinidad and Tobago",
        "TN": "Tunisia",
        "TR": ["Türkiye","Turkey"],
        "TM": "Turkmenistan",
        "TC": "Turks and Caicos Islands",
        "TV": "Tuvalu",
        "UG": "Uganda",
        "UA": "Ukraine",
        "AE": "United Arab Emirates",
        "GB": ["United Kingdom", "UK", "Great Britain"],
        "US": ["United States of America", "United States", "USA", "U.S.A.", "US", "U.S."],
        "UM": "United States Minor Outlying Islands",
        "UY": "Uruguay",
        "UZ": "Uzbekistan",
        "VU": "Vanuatu",
        "VE": "Venezuela",
        "VN": "Vietnam",
        "VG": "Virgin Islands, British",
        "VI": "Virgin Islands, U.S.",
        "WF": "Wallis and Futuna",
        "EH": "Western Sahara",
        "YE": "Yemen",
        "ZM": "Zambia",
        "ZW": "Zimbabwe",
        "AX": "Åland Islands",
        "BQ": "Bonaire, Sint Eustatius and Saba",
        "CW": "Curaçao",
        "GG": "Guernsey",
        "IM": "Isle of Man",
        "JE": "Jersey",
        "ME": "Montenegro",
        "BL": "Saint Barthélemy",
        "MF": "Saint Martin (French part)",
        "RS": "Serbia",
        "SX": "Sint Maarten (Dutch part)",
        "SS": "South Sudan",
        "XK": "Kosovo"
      }
    },
    {
      "locale": "es",
      "countries": {
        "AF": "Afganistán",
        "AL": "Albania",
        "DZ": "Argelia",
        "AS": "Samoa Americana",
        "AD": "Andorra",
        "AO": "Angola",
        "AI": "Anguila",
        "AQ": "Antártida",
        "AG": "Antigua y Barbuda",
        "AR": "Argentina",
        "AM": "Armenia",
        "AW": "Aruba",
        "AU": "Australia",
        "AT": "Austria",
        "AZ": "Azerbaiyán",
        "BS": "Bahamas",
        "BH": "Bahrein",
        "BD": "Bangladesh",
        "BB": "Barbados",
        "BY": "Bielorrusia",
        "BE": "Bélgica",
        "BZ": "Belice",
        "BJ": "Benin",
        "BM": "Bermudas",
        "BT": "Bután",
        "BO": "Bolivia",
        "BA": "Bosnia y Herzegovina",
        "BW": "Botswana",
        "BV": "Isla Bouvet",
        "BR": "Brasil",
        "IO": "Territorio Británico del Océano Índico",
        "BN": "Brunei Darussalam",
        "BG": "Bulgaria",
        "BF": "Burkina Faso",
        "BI": "Burundi",
        "KH": "Camboya",
        "CM": "Camerún",
        "CA": "Canadá",
        "CV": "Cabo Verde",
        "KY": "Islas Caimán",
        "CF": "República Centroafricana",
        "TD": "Chad",
        "CL": "Chile",
        "CN": "China",
        "CX": "Isla de Navidad",
        "CC": "Islas Cocos (Keeling)",
        "CO": "Colombia",
        "KM": "Comoras",
        "CG": "Congo",
        "CD": "Congo (República Democrática del)",
        "CK": "Islas Cook",
        "CR": "Costa Rica",
        "CI": "Costa de Marfil",
        "HR": "Croacia",
        "CU": "Cuba",
        "CY": "Chipre",
        "CZ": "República Checa",
        "DK": "Dinamarca",
        "DJ": "Yibuti",
        "DM": "Dominica",
        "DO": "República Dominicana",
        "EC": "Ecuador",
        "EG": "Egipto",
        "SV": "El Salvador",
        "GQ": "Guinea Ecuatorial",
        "ER": "Eritrea",
        "EE": "Estonia",
        "ET": "Etiopía",
        "FK": "Islas Malvinas",
        "FO": "Islas Feroe",
        "FJ": "Fiji",
        "FI": "Finlandia",
        "FR": "Francia",
        "GF": "Guayana Francesa",
        "PF": "Polinesia Francesa",
        "TF": "Tierras Australes Francesas",
        "GA": "Gabón",
        "GM": "Gambia",
        "GE": "Georgia",
        "DE": "Alemania",
        "GH": "Ghana",
        "GI": "Gibraltar",
        "GR": "Grecia",
        "GL": "Groenlandia",
        "GD": "Granada",
        "GP": "Guadalupe",
        "GU": "Guam",
        "GT": "Guatemala",
        "GN": "Guinea",
        "GW": "Guinea Bissau",
        "GY": "Guyana",
        "HT": "Haití",
        "HM": "Heard e Islas McDonald",
        "VA": "Santa Sede",
        "HN": "Honduras",
        "HK": "Hong Kong",
        "HU": "Hungría",
        "IS": "Islandia",
        "IN": "India",
        "ID": "Indonesia",
        "IR": ["Irán", "República Islámica de Irán"],
        "IQ": "Iraq",
        "IE": "Irlanda",
        "IL": "Israel",
        "IT": "Italia",
        "JM": "Jamaica",
        "JP": "Japón",
        "JO": "Jordania",
        "KZ": "Kazajistán",
        "KE": "Kenia",
        "KI": "Kiribati",
        "KP": "República Popular Democrática de Corea",
        "KR": "República de Corea",
        "KW": "Kuwait",
        "KG": "Kirguistán",
        "LA": "República Democrática Popular de Lao",
        "LV": "Letonia",
        "LB": "Líbano",
        "LS": "Lesoto",
        "LR": "Liberia",
        "LY": "Libia",
        "LI": "Liechtenstein",
        "LT": "Lituania",
        "LU": "Luxemburgo",
        "MO": "Macao",
        "MK": "Macedonia del Norte",
        "MG": "Madagascar",
        "MW": "Malaui",
        "MY": "Malasia",
        "MV": "Maldivas",
        "ML": "Malí",
        "MT": "Malta",
        "MH": "Islas Marshall",
        "MQ": "Martinica",
        "MR": "Mauritania",
        "MU": "Mauricio",
        "YT": "Mayotte",
        "MX": "México",
        "FM": "Micronesia",
        "MD": "Moldavia",
        "MC": "Mónaco",
        "MN": "Mongolia",
        "MS": "Montserrat",
        "MA": "Marruecos",
        "MZ": "Mozambique",
        "MM": "Myanmar",
        "NA": "Namibia",
        "NR": "Nauru",
        "NP": "Nepal",
        "NL": "Países Bajos",
        "NC": "Nueva Caledonia",
        "NZ": "Nueva Zelanda",
        "NI": "Nicaragua",
        "NE": "Níger",
        "NG": "Nigeria",
        "NU": "Niue",
        "NF": "Isla Norfolk",
        "MP": "Islas Marianas del Norte",
        "NO": "Noruega",
        "OM": "Omán",
        "PK": "Pakistán",
        "PW": "Palau",
        "PS": "Palestina",
        "PA": "Panamá",
        "PG": "Papua Nueva Guinea",
        "PY": "Paraguay",
        "PE": "Perú",
        "PH": "Filipinas",
        "PN": "Pitcairn",
        "PL": "Polonia",
        "PT": "Portugal",
        "PR": "Puerto Rico",
        "QA": "Catar",
        "RE": "Reunión",
        "RO": "Rumanía",
        "RU": "Rusia",
        "RW": "Ruanda",
        "SH": "Santa Helena, Ascensión y Tristán de Acuña",
        "KN": "Saint Kitts y Nevis",
        "LC": "Santa Lucía",
        "PM": "San Pedro y Miquelón",
        "VC": "San Vicente y las Granadinas",
        "WS": "Samoa",
        "SM": "San Marino",
        "ST": "Santo Tomé y Príncipe",
        "SA": "Arabia Saudita",
        "SN": "Senegal",
        "SC": "Seychelles",
        "SL": "Sierra Leona",
        "SG": "Singapur",
        "SK": "Eslovaquia",
        "SI": "Eslovenia",
        "SB": "Islas Salomón",
        "SO": "Somalia",
        "ZA": "Sudáfrica",
        "GS": "Georgia del Sur y las Islas Sandwich del Sur",
        "ES": "España",
        "LK": "Sri Lanka",
        "SD": "Sudán",
        "SR": "Suriname",
        "SJ": "Svalbard y Jan Mayen",
        "SZ": "Esuatini",
        "SE": "Suecia",
        "CH": "Suiza",
        "SY": "República Árabe Siria",
        "TW": "Taiwán",
        "TJ": "Tayikistán",
        "TZ": "Tanzania",
        "TH": "Tailandia",
        "TL": "Timor-Leste",
        "TG": "Togo",
        "TK": "Tokelau",
        "TO": "Tonga",
        "TT": "Trinidad y Tobago",
        "TN": "Túnez",
        "TR": "Turquía",
        "TM": "Turkmenistán",
        "TC": "Islas Turcas y Caicos",
        "TV": "Tuvalu",
        "UG": "Uganda",
        "UA": "Ucrania",
        "AE": "Emiratos Árabes Unidos",
        "GB": "Reino Unido",
        "US": "Estados Unidos",
        "UM": "Islas Ultramarinas Menores de los Estados Unidos",
        "UY": "Uruguay",
        "UZ": "Uzbekistán",
        "VU": "Vanuatu",
        "VE": "Venezuela",
        "VN": "Vietnam",
        "VG": "Islas Vírgenes británicas",
        "VI": "Islas Vírgenes de los Estados Unidos",
        "WF": "Wallis y Futuna",
        "EH": "Sahara Occidental",
        "YE": "Yemen",
        "ZM": "Zambia",
        "ZW": "Zimbabue",
        "AX": "Islas Åland",
        "BQ": "Bonaire, San Eustaquio y Saba",
        "CW": "Curaçao",
        "GG": "Guernsey",
        "IM": "Isla de Man",
        "JE": "Jersey",
        "ME": "Montenegro",
        "BL": "Saint Barthélemy",
        "MF": "Saint Martin (francesa)",
        "RS": "Serbia",
        "SX": "Sint Maarten (neerlandesa)",
        "SS": "Sudán del Sur",
        "XK": "Kosovo"
      }
    }
  ];
};