// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  key_facts: defineAsyncComponent(() => import("./KeyFacts/index.vue")),
  our_clients: defineAsyncComponent(() => import("./OurClients/index.vue")),
  service_type: defineAsyncComponent(() => import("./ServiceType/index.vue")),
  services_reason: defineAsyncComponent(
    () => import("./ServicesReason/index.vue")
  ),
  testimonials: defineAsyncComponent(() => import("./Testimonials/index.vue")),
});
