// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  callout_text_content: defineAsyncComponent(
    () => import("./CalloutTextContent/index.vue"),
  ),
  image_text: defineAsyncComponent(() => import("./ImageText/index.vue")),
  image_text_box: defineAsyncComponent(
    () => import("./ImageTextBox/index.vue"),
  ),
  images_grid: defineAsyncComponent(() => import("./ImagesGrid/index.vue")),
  our_clients: defineAsyncComponent(() => import("./ClientLogos/index.vue")),
  page_hero: defineAsyncComponent(() => import("./PageHero/index.vue")),
  service_type: defineAsyncComponent(() => import("./Accordion/index.vue")),
  services_reason: defineAsyncComponent(
    () => import("./ServicesReason/index.vue"),
  ),
  services_slider: defineAsyncComponent(
    () => import("./ServicesSlider/index.vue"),
  ),
  testimonials: defineAsyncComponent(() => import("./Testimonials/index.vue")),
  text_block: defineAsyncComponent(() => import("./TextBlock/index.vue")),
});
